#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# SPDX Header Validation for Source Files

set -euo pipefail
SCAN_PATH="${INPUT_PATH:-.}"
STAGED_FILES="${INPUT_STAGED_FILES:-}"
ERRORS=0

# The single authority for "does this path need an SPDX header".
#
# ⚠ THIS FUNCTION EXISTS BECAUSE THE TWO MODES BELOW USED TO ASK DIFFERENT
# QUESTIONS. Full-scan mode filtered by source extension inside `find`; staged
# mode had NO filter at all (`FILES_TO_CHECK=$STAGED_FILES`) and so demanded a
# header on EVERY staged path. That is not a cosmetic split, because only the
# staged branch is reachable: this validator is called from .githooks/pre-commit
# and from no workflow at all, so the mode that HAD the filter never ran and the
# mode that ran had none.
#
# The concrete casualty was .github/workflows/actions.lock. It is generated by
# `gh actions-lock` ("Do not edit by hand"), carries no header, and is restamped
# on every regeneration — so a header added by hand does not survive. No commit
# touching the lockfile could pass pre-commit, which is why a Dependabot-caused
# lockfile desync could sit unrepaired long enough to recur (see #746).
#
# Keep ONE list. If a mode ever needs a different rule, that is a new function
# with a name saying so, never a second copy of these patterns.
is_source_file() {
  case "$1" in
    *.rs|*.res|*.js|*.ts|*.sh|*.bash|*.zig|*.ex|*.exs|*.gleam|\
    *.ml|*.mli|*.adb|*.ads|*.ncl|*.toml|*.json|*.yaml|*.yml) return 0 ;;
    *) return 1 ;;
  esac
}

# If staged files provided, only check those
if [ -n "$STAGED_FILES" ]; then
  FILES_TO_CHECK=$STAGED_FILES
else
  # Every candidate file; is_source_file below decides which ones count.
  FILES_TO_CHECK=$(find "$SCAN_PATH" -path '*/.git/*' -prune -o -path '*/node_modules/*' -prune -o \
    -type f -print 2>/dev/null || true)
fi

[ -z "$FILES_TO_CHECK" ] && exit 0

for file in $FILES_TO_CHECK; do
  [ -f "$file" ] || continue
  is_source_file "$file" || continue

  # Check for SPDX header in first 10 lines
  if ! head -10 "$file" | grep -qE '^# SPDX-License-Identifier:'; then
    echo "[validate-spdx] ERROR: $file missing SPDX header" >&2
    ERRORS=$((ERRORS + 1))
  fi
done

[ $ERRORS -gt 0 ] && exit 1
echo "[validate-spdx] ✅ All source files have SPDX headers"
exit 0
