# SPDX-License-Identifier: MPL-2.0-or-later
# SPDX-FileCopyrightText: 2024-2025 Palimpsest Stewardship Council

resolver: lts-20.26  # GHC 9.2.8

packages:
  - .

extra-deps: []

# Build settings
build:
  library-profiling: false
  executable-profiling: false
  copy-bins: true
  haddock: false

# Allow newer versions for compatibility
allow-newer: true
