# SPDX-License-Identifier: MPL-2.0
# Blank issues are disabled deliberately.
# Intake Spec (docs/ISSUE-INTAKE-SPEC.adoc) Rule 4: an issue that fits none of
# the templates (bug / decision / campaign) does not fit this repository.
# The blank form is how the 2026-09-22 unstructured bulk-filing shape becomes
# possible again; it is not an acceptable intake path.
blank_issues_enabled: false
