# SPDX-License-Identifier: MPL-2.0
name: OSSF Scorecard

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    uses: ../../../../.github/workflows/scorecard-reusable.yml
    secrets: inherit
