#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
#
# Tests for .githooks/validate-spdx.sh, the pre-commit gate.
#
# ⚠ TEST 1 IS THE REASON THIS EXISTS, and it FAILS against the previous version.
#
# The validator had two modes asking two different questions. Full-scan mode
# filtered by source extension inside `find`; staged mode did not filter at all:
#
#     FILES_TO_CHECK=$STAGED_FILES        # every staged path, whatever it is
#
# Only the staged branch is reachable in practice — this validator is invoked by
# .githooks/pre-commit and by no workflow — so the mode that HAD the filter never
# ran, and the mode that ran had none.
#
# The casualty was .github/workflows/actions.lock: machine-generated by
# `gh actions-lock`, headerless by construction, and restamped on every
# regeneration so a hand-added header does not survive. Every commit touching the
# lockfile was therefore unpassable, which is how a Dependabot-caused lockfile
# desync survived long enough to recur (precedent: #746).
#
# Test 1 is the planted positive for that: staging a headerless .lock file must
# PASS. Test 4 is the parity check that the two modes now ask the same question,
# because a filter that exists in only one mode is what caused this.
set -uo pipefail
HOOK="$(cd "$(dirname "$0")/../.." && pwd)/.githooks/validate-spdx.sh"
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
mkdir -p "$T/.github/workflows"
pass=0; fail=0

ck() { # name expected_exit staged_files
  local out rc
  out="$(cd "$T" && INPUT_STAGED_FILES="$3" bash "$HOOK" 2>&1)"; rc=$?
  if [ "$rc" = "$2" ]; then printf '  ok    %s (exit %s)\n' "$1" "$rc"; pass=$((pass+1))
  else printf '  FAIL  %s (expected exit %s, got %s) output=%s\n' "$1" "$2" "$rc" "${out:-<none>}"; fail=$((fail+1)); fi
}

ck_scan() { # name expected_exit path
  local out rc
  out="$(cd "$T" && INPUT_PATH="$3" bash "$HOOK" 2>&1)"; rc=$?
  if [ "$rc" = "$2" ]; then printf '  ok    %s (exit %s)\n' "$1" "$rc"; pass=$((pass+1))
  else printf '  FAIL  %s (expected exit %s, got %s) output=%s\n' "$1" "$2" "$rc" "${out:-<none>}"; fail=$((fail+1)); fi
}

# A real actions.lock preamble: the tool's own banner, and no SPDX line anywhere.
printf "# This file is machine-generated by \`gh actions-lock\`.\n# Do not edit by hand; run \`gh actions-lock\` to update.\nversion: 'v0.0.2'\n" \
  > "$T/.github/workflows/actions.lock"
printf '# SPDX-License-Identifier: MPL-2.0\necho ok\n' > "$T/good.sh"
printf 'echo bad\n'                                    > "$T/bad.sh"
printf 'name: bad\non: push\n'                         > "$T/.github/workflows/bad.yml"
printf 'binary-ish payload, not source\n'              > "$T/README.md"

echo "validate-spdx.sh"
ck "PLANTED POSITIVE: headerless actions.lock must PASS" 0 ".github/workflows/actions.lock"
ck "negative control: headerless .sh must FAIL"          1 "good.sh bad.sh"
ck "negative control: headerless .yml must FAIL"         1 ".github/workflows/bad.yml"
ck "valid header must PASS"                              0 "good.sh"
ck "non-source README.md must PASS"                      0 "README.md"
ck "lockfile alongside a valid source file must PASS"    0 ".github/workflows/actions.lock good.sh"

# PARITY: both modes must agree about the same tree. A tree whose only headerless
# files are non-source must pass a full scan exactly as it passes staged mode.
mkdir -p "$T/parity"
cp "$T/.github/workflows/actions.lock" "$T/parity/actions.lock"
cp "$T/README.md" "$T/parity/README.md"
cp "$T/good.sh"   "$T/parity/good.sh"
ck_scan "PARITY: full-scan mode ignores the same non-source files" 0 "parity"

# RSR COVERAGE: .scm files carry `;;`-style headers and must be checked
# (previously the extension list skipped them, so a staged RSR seed file
# passed without its required header). Empty identifiers and trailing junk
# must fail: they pass a prefix check but fail SPDX tooling.
printf ';; SPDX-License-Identifier: MPL-2.0\n(display 1)\n' > "$T/good.scm"
printf ';;; SPDX-License-Identifier: MPL-2.0\n;;; banner\n' > "$T/banner.scm"
printf '(display 1)\n' > "$T/bad.scm"
printf ';; SPDX-License-Identifier:\n(display 1)\n' > "$T/empty.scm"
printf '# SPDX-License-Identifier: MPL-2.0; copyright me\necho\n' > "$T/junk.sh"
printf '(* SPDX-License-Identifier: MIT *)\n' > "$T/good.ml"
ck "scm with ;; header must PASS" 0 "good.scm"
ck "scm with ;;; banner header must PASS" 0 "banner.scm"
ck "headerless .scm must FAIL" 1 "bad.scm"
ck "empty SPDX identifier must FAIL" 1 "empty.scm"
ck "trailing junk after expression must FAIL" 1 "junk.sh"
ck "OCaml (* *) terminator must PASS" 0 "good.ml"

printf '\n%s passed, %s failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ] || exit 1
