// Generated by ReScript, PLEASE EDIT WITH CARE


let getArrayLength = (function(arr) { return arr.length });

let getArrayItem = (function(arr, i) { return arr[i] });

function parseKeyValue(segment) {
  let trimmed = segment.trim();
  let parts = trimmed.split("=");
  let len = getArrayLength(parts);
  if (len < 2) {
    return;
  }
  let key = getArrayItem(parts, 0).trim();
  let value = parts.slice(1).join("=").trim();
  return [
    key,
    value
  ];
}

function parse(payload) {
  let trimmed = payload.trim();
  if (trimmed.length === 0) {
    return {
      TAG: "Error",
      _0: {
        TAG: "MalformedRecord",
        _0: "empty payload"
      }
    };
  }
  let segments = trimmed.split(";");
  let version;
  let id;
  let segmentCount = getArrayLength(segments);
  for (let i = 0; i < segmentCount; ++i) {
    let segment = getArrayItem(segments, i);
    let match = parseKeyValue(segment);
    if (match !== undefined) {
      switch (match[0]) {
        case "id" :
          id = match[1];
          break;
        case "v" :
          version = match[1];
          break;
      }
    }
  }
  let match$1 = version;
  let match$2 = id;
  if (match$1 !== undefined) {
    if (match$1 !== "AXEL1") {
      return {
        TAG: "Error",
        _0: {
          TAG: "InvalidVersion",
          _0: match$1
        }
      };
    } else if (match$2 !== undefined) {
      if (match$2.trim().length === 0) {
        return {
          TAG: "Error",
          _0: "EmptyId"
        };
      } else {
        return {
          TAG: "Ok",
          _0: {
            version: match$1,
            id: match$2.trim()
          }
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: "MissingId"
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: "MissingVersion"
    };
  }
}

function errorToString(err) {
  if (typeof err === "object") {
    if (err.TAG === "InvalidVersion") {
      return "Invalid version: '" + err._0 + "' (expected 'AXEL1')";
    } else {
      return "Malformed record: " + err._0;
    }
  }
  switch (err) {
    case "MissingVersion" :
      return "Missing required field: v (version)";
    case "MissingId" :
      return "Missing required field: id";
    case "EmptyId" :
      return "Empty id field (must be non-empty)";
  }
}

export {
  getArrayLength,
  getArrayItem,
  parseKeyValue,
  parse,
  errorToString,
}
/* No side effect */
