// Generated by ReScript, PLEASE EDIT WITH CARE


function msg(_msg) {
  
}

let Cmd = {
  none: undefined,
  msg: msg
};

let Sub = {
  none: undefined
};

function text(str) {
  return str;
}

function tag(tagName, _attrs, children) {
  let childrenHtml = (children.map(c => c).join(''));
  return `<` + tagName + `>` + childrenHtml + `</` + tagName + `>`;
}

function div(attrs, children) {
  return tag("div", attrs, children);
}

function p(attrs, children) {
  return tag("p", attrs, children);
}

function h2(attrs, children) {
  return tag("h2", attrs, children);
}

function h3(attrs, children) {
  return tag("h3", attrs, children);
}

function h4(attrs, children) {
  return tag("h4", attrs, children);
}

function pre(attrs, children) {
  return tag("pre", attrs, children);
}

function code(attrs, children) {
  return tag("code", attrs, children);
}

function button(attrs, children) {
  return tag("button", attrs, children);
}

function section(attrs, children) {
  return tag("section", attrs, children);
}

function class$p(name) {
  return `class="` + name + `"`;
}

function id(name) {
  return `id="` + name + `"`;
}

function onClick(_handler) {
  return "";
}

let Html = {
  noNode: "",
  text: text,
  tag: tag,
  div: div,
  p: p,
  h2: h2,
  h3: h3,
  h4: h4,
  pre: pre,
  code: code,
  button: button,
  section: section,
  class$p: class$p,
  id: id,
  onClick: onClick
};

function standardProgram(program) {
  let match = program.init();
  let html = program.view(match[0]);
  let el = document.getElementById("tea-app");
  if (el == null) {
    console.log("TEA mount point #tea-app not found");
  } else {
    el.innerHTML = html;
  }
}

let App = {
  standardProgram: standardProgram
};

export {
  Cmd,
  Sub,
  Html,
  App,
}
/* No side effect */
