// Generated by ReScript, PLEASE EDIT WITH CARE


function init() {
  return {
    domainToCheck: "example.com",
    currentRating: "NotLabeled",
    domainValid: false
  };
}

function validateDomain(domain) {
  let domainLen = domain.length;
  if (domainLen > 0) {
    return (domain.includes("."));
  } else {
    return false;
  }
}

function update(model, msg) {
  if (msg.TAG !== "CheckDomain") {
    return {
      domainToCheck: model.domainToCheck,
      currentRating: msg._0,
      domainValid: model.domainValid
    };
  }
  let domain = msg._0;
  let valid = validateDomain(domain);
  return {
    domainToCheck: domain,
    currentRating: model.currentRating,
    domainValid: valid
  };
}

function ratingToString(rating) {
  switch (rating) {
    case "NotLabeled" :
      return "Not Labeled";
    case "SafeForWork" :
      return "Safe for Work";
    case "AdultContent" :
      return "Adult Content (18+)";
    case "Explicit" :
      return "Explicit Content";
  }
}

function render(model) {
  return "AXEL Label Checker - Domain: " + model.domainToCheck + " | Valid: " + (
    model.domainValid ? "✓" : "✗"
  ) + " | Rating: " + ratingToString(model.currentRating);
}

export {
  init,
  validateDomain,
  update,
  ratingToString,
  render,
}
/* No side effect */
