// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function fromJs(jsResult) {
  if (jsResult.ok) {
    let v = jsResult.value;
    if (v !== undefined) {
      return {
        TAG: "Ok",
        _0: Primitive_option.valFromOption(v)
      };
    } else {
      return {
        TAG: "Error",
        _0: "Ok result missing value"
      };
    }
  }
  let e = jsResult.error;
  if (e !== undefined) {
    return {
      TAG: "Error",
      _0: e
    };
  } else {
    return {
      TAG: "Error",
      _0: "Unknown error"
    };
  }
}

function toJs(result) {
  if (result.TAG === "Ok") {
    return {
      ok: true,
      value: Primitive_option.some(result._0),
      error: undefined
    };
  } else {
    return {
      ok: false,
      value: undefined,
      error: result._0
    };
  }
}

export {
  fromJs,
  toJs,
}
/* No side effect */
