// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProvenResult from "./ProvenResult.res.js";
import * as Safe_url from "proven/safe_url";

let SafeUrlJs = {};

function parse(urlString, base) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.parse(urlString, base));
}

function isValid(prim) {
  return Safe_url.SafeUrl.isValid(prim);
}

function getQueryParam(urlString, param) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.getQueryParam(urlString, param));
}

function getQueryParams(urlString) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.getQueryParams(urlString));
}

function setQueryParam(urlString, param, value) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.setQueryParam(urlString, param, value));
}

function removeQueryParam(urlString, param) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.removeQueryParam(urlString, param));
}

function join(base, paths) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.join(base, paths));
}

function getDomain(urlString) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.getDomain(urlString));
}

function isHttps(prim) {
  return Safe_url.SafeUrl.isHttps(prim);
}

function encode(prim) {
  return Safe_url.SafeUrl.encode(prim);
}

function decode(str) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.decode(str));
}

function normalize(urlString) {
  return ProvenResult.fromJs(Safe_url.SafeUrl.normalize(urlString));
}

export {
  SafeUrlJs,
  parse,
  isValid,
  getQueryParam,
  getQueryParams,
  setQueryParam,
  removeQueryParam,
  join,
  getDomain,
  isHttps,
  encode,
  decode,
  normalize,
}
/* proven/safe_url Not a pure module */
