# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
name: Governance

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  governance:
    uses: ./.github/workflows/governance-reusable.yml@6bb17de833ab06bab4f5b8e852eb012b1ac08f05
