# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
name: Mirror to Git Forges

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  mirror:
    uses: hyperpolymath/standards/.github/workflows/mirror-reusable.yml@70cdad0e95bb2366a9b2ae9789c0e377fef6e3ef
    secrets: inherit
