# This workflow is managed by gh actions-lock.
# SPDX-License-Identifier: MPL-2.0
name: README Derive

on:
  push:
    branches: [main, master]
    paths:
      - 'README.adoc'
      - '.publishing.readme'
  pull_request:
    branches: [main, master]
    paths:
      - 'README.adoc'
      - '.publishing.readme'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  derive:
    uses: ./.github/workflows/readme-derive-reusable.yml
