# SPDX-License-Identifier: MPL-2.0
# Self-CI: Call our own ci-pipeline.yml reusable workflow
# This ensures the pipeline we publish is consumed by ourselves (AC6 of #986)

{
  name: "Self-CI",
  on: {
    push: {
      branches: [
        "main",
      ],
    },
    pull_request: {
      branches: [
        "main",
      ],
    },
    schedule: [
      {
        cron: "0 0 * * 0", # Weekly Sunday midnight
      },
    ],
  },
  permissions: {
    contents: "read",
  },
  jobs: {
    call-ci-pipeline: {
      name: "Call CI Pipeline",
      uses: "./.github/workflows/ci-pipeline.yml",
    },
  },
}
