// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Nodecrypto from "node:crypto";

function make(config) {
  return {
    sessions: {},
    config: config
  };
}

function createSession(manager, repoPath) {
  let session_sessionId = Nodecrypto.randomUUID();
  let session = {
    sessionId: session_sessionId,
    acknowledgedManifest: false,
    attestationHash: undefined,
    acknowledgedAt: undefined,
    repoPath: repoPath
  };
  manager.sessions[session_sessionId] = session;
  setTimeout(() => {
    manager.sessions[session_sessionId] = session;
  }, manager.config.sessionTimeout);
  return session;
}

function getSession(manager, sessionId) {
  return manager.sessions[sessionId];
}

function acknowledgeManifest(manager, sessionId, manifest, attestationHash) {
  let session = manager.sessions[sessionId];
  if (session === undefined) {
    return false;
  }
  if (manifest.hash !== attestationHash) {
    return false;
  }
  let updatedSession_sessionId = session.sessionId;
  let updatedSession_attestationHash = attestationHash;
  let updatedSession_acknowledgedAt = new Date();
  let updatedSession_repoPath = session.repoPath;
  let updatedSession = {
    sessionId: updatedSession_sessionId,
    acknowledgedManifest: true,
    attestationHash: updatedSession_attestationHash,
    acknowledgedAt: updatedSession_acknowledgedAt,
    repoPath: updatedSession_repoPath
  };
  manager.sessions[sessionId] = updatedSession;
  return true;
}

function isAcknowledged(manager, sessionId) {
  let session = manager.sessions[sessionId];
  if (session !== undefined) {
    return session.acknowledgedManifest;
  } else {
    return false;
  }
}

function destroySession(manager, sessionId) {
  manager.sessions[sessionId] = Belt_Option.getExn(manager.sessions[sessionId]);
}

function getActiveSessions(manager) {
  return Object.values(manager.sessions);
}

let SessionManager = {
  make: make,
  createSession: createSession,
  getSession: getSession,
  acknowledgeManifest: acknowledgeManifest,
  isAcknowledged: isAcknowledged,
  destroySession: destroySession,
  getActiveSessions: getActiveSessions
};

export {
  SessionManager,
}
/* node:crypto Not a pure module */
